fetch('/main.tpl.html'.toString('url')).then(res =>
  res.text().then(console.log)
);

// Generated by CoffeeScript 2.3.0
(function() {
  var square;

  square = function(x) {
    return x * x;
  };

  alert(square(10));
}.call(this));

// # sourceMappingURL=main.js.map
